2e Character sheet alignment with Modiphius version
mkscho63/sta pull request #126
Opened 2024-08-08 10:09 UTC by tokeidlom

- Addition of Acclaim/Reprimand
- Addition of pastime
- Addition of career path
- Addition of career events

2024-08-08 19:40 UTC, WesWedding commented on src/template.json
The new lines here use different whitespace compared to the rest of the file.  Tabs vs spaces.

2024-08-08 19:42 UTC, WesWedding requested changes
Visually things look good.  This isn't fully in alignment with the sheets, though.  Pronouns and Special Rules seem to be missing.

There is an HTML error that is not visual that should probably be address, however; the Acc/Rep input elements have inherited the strmod input's ID attribute.

2024-08-08 19:57 UTC, tokeidlom commented
Whitespace made consistent, ids removed from the acclaim and reprimand lines as they aren't called from anywhere, just for users to see on the sheet. Thanks for spotting that!

2024-08-09 15:44 UTC, mkscho63 approved these changes

2024-08-09 15:44 UTC, merged