Klingon and acclaim
mkscho63/sta pull request #160
Opened 2024-10-06 14:52 UTC by tokeidlom

Adding Klingon character sheet and acclaim support to 1e character sheet

2024-10-06 14:52 UTC, tokeidlom commented on src/lang/pt.json
Would you like to review this before it gets merged @adambravo79 ?

2024-10-06 16:14 UTC, adambravo79 commented on src/lang/pt.json
Will do

2024-10-06 16:21 UTC, adambravo79 commented on src/lang/pt.json
> +  "sta.actor.character.klingon.might": "Força",
might is better translated as: "Poder"

2024-10-06 16:23 UTC, adambravo79 requested changes
It is okay, just recommend to change the 'might' string to "Poder".

2024-10-06 16:53 UTC, tokeidlom commented on src/lang/pt.json
> +  "sta.actor.character.klingon.might": "Força",
Done, thank you!

2024-10-07 17:15 UTC, WesWedding reviewed
There's a lot to review here!

----
Making sure that all fields are included from the printed sheet is an admirable goal but I feel that the Klingon variant is quite overwhelmingly detailed at this point.  To the point of making it actually hard to use, even.  Many of the fields aren't Klingon-specific, either, so hiding them solely on the Klingon setting seems wrong to me.

Perhaps a new section of inputs needs to be introduced at the very bottom of the sheet to where fields can live, so we're not pushing the Attribs, Disciplines, Belongings, etc lower and lower.

----
Acclaim/Reprimand and Reputation should probably be closer to the reputation bar, since they're so closely linked conceptually.  Making them on opposite sides of the fields introduces a spatial and conceptual separation.  

----
Putting all of those extra fields for Klingon stuff behind a Setting seems counterintuitive to me.

If I were a user and wanted to have a Klingon sheet I think I would expect to be able to just switch to a Klingon sheet using the normal Foundry workflow.
![image](https://github.com/user-attachments/assets/14e47f11-b1fe-4ef3-9fa4-59a226f191b3)

----
From a developer perspective, when a "if" block gets especially massive, that tends to be a code smell to me;  I start to look for a way to move all of that nested logic into a new function.

I feel like this extends to the HBS file, too.  Seems like a good case for using Handlebars partials when an `{{if}}` is wrapped around simply massive chunks of HTML.

----
Lots of hardcoded `width=X%` which, unfortunately, was done earlier in System development and we're sort of just continuing to expand as new fields come in.  Generally if there's a style that needs to be applied it should be done in CSS, so it's easier to find.  Something that probably deserves a cleanup later, I guess!

2024-10-07 17:15 UTC, WesWedding commented on src/module/actors/sheets/character-sheet.js
> +  <form class="sta-form">
Maybe this should live in a Handlebars file instead of being hardcoded here.

2024-10-08 15:59 UTC, tokeidlom commented
I end up with a sheet that looks something like this:
![image](https://github.com/user-attachments/assets/c7c8130f-5520-4ca2-9f79-42f809277e24)

2024-10-08 17:26 UTC, WesWedding commented
Another brainstorm idea for managing space is that comes to mind is [collapsible ](https://www.w3schools.com/howto/howto_js_collapsible.asp )sections.   It might require some reworking, but you could have some collections of fields come pre-collapsed, but maybe that would be a win.  A downside of collapsible sections is that usually mean that the uncollapsed state is even taller than what it was before the fields got wrapped, though.

2024-10-08 18:13 UTC, WesWedding commented
I like that grouping of rep at the bottom, looks slick.

2024-10-10 16:06 UTC, tokeidlom commented
Alternatively there is another path we could take (these are a basic mock up as a proof on concept, not a finished product), I would need to know if this is a route we wanted to take before sinking more time into this as it'll be a massive job!
![image](https://github.com/user-attachments/assets/936f7962-32a1-4519-b98d-0b7d1d5b40e8)
![image](https://github.com/user-attachments/assets/e94a9900-4709-47b5-8a7c-d3bea48f5093)
![image](https://github.com/user-attachments/assets/50cf2c5e-e059-4262-99d5-d11d53ee5f73)
![image](https://github.com/user-attachments/assets/30cadf2c-22f8-42c6-9c86-68fad9da1d11)

2024-10-10 16:27 UTC, WesWedding commented
I wish there was a way to solicit user feedback on this!  Organizing things seems like a good spot for at least collecting feedback.

There's always tradeoffs to approaches and even though I favor Tabs over other approaches, we might as well acknowledge one downside that has come in in convo about tabs before which is: it can get a little disorienting having to switch tabs.  Especially in STA.

Unlike other some RPG systems, almost every Task including combat includes a broad spectrum of mechanics to consider.  And this system doesn't automate much, so the player has to keep track of all these mechanics every roll (and, in my GM experience, I have to guide them through it every time).

The list is long, especially in combat.  You have to review Attributes, Disciplines, Traits, Values, Focuses, Weapons, Armor (maybe more?).   So splitting Items from Values, Focuses, etc is actually a little bit annoying or even disorienting.  Or at least, I have occasionally found it disorienting when I'm a GM bouncing around multiple characters that might all be on different tabs.  Even a non-combat Task could require switching tabs if it involves inventory.

However, the upsides of Tabs are incredibly obvious.  You get a more compact sheet, you get to be more free with new fields, it means there is room to actually add some missing stuff like Milestones in the future, and so on.

2024-10-10 16:37 UTC, WesWedding commented
I am personally in favor of the overall layout you're suggesting, it's extremely similar to something I wanted to do in STA Enhanced eventually but it was going to be a lot more work than just adding some tabs.  I think either DND5E or Pathfinder used a similar layout, where it has a sidebar with the primary stats.

I think maybe a "Community Feedback: Sheet Reorganizing" or maybe even something attention-getting like "Community Feedback: Character Sheet 2.0" issue in the Issue queue would be good idea, with mockups posted (without LCARS, too) just to see what people think before making a commitment to the work.

2024-10-10 18:12 UTC, tokeidlom commented
I could move the species row into the bio tab which would mean all the items sheets could probably be put into one tab.

What's required for milestones? Would another text field similar to notes, but dedicated to milestones be adequate?

2024-10-10 18:30 UTC, WesWedding commented
It depends entirely on how feature-rich the system goes, you know?  There is currently an unfinished Milestone item already in the system, so that could be built up a bit.  And then that leads to a conversation about what goes in the item...  A field for the value used?  A negative, positive, challenge indicator?  Track the reward used?  Flag it as a character arc?

Mission logs are also a key part of the Milestone system.  Should that be an Item? Where should we store those?

We shouldn't have that discussion in this thread, though.  This PR is about supporting Klingon and acclaim.  If the sheet redesign has to come first, then I feel like this PR should be put on hold and sheet redesign needs to go somewhere else.

2024-10-12 08:02 UTC, closed without merging